ShopBCH/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('product/', include('product.urls')),
    path('user/', include('user.urls')),
    path('order/', include('order.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from .views import HomeView
from django.urls import path
app_name = 'Home'
urlpatterns = [
    path('',HomeView.as_view(), name='home' ),
]

order/urls.py
from django.urls import path,include
from . import views

app_name = 'Order'
urlpatterns =[
    path("new-order/", views.CreateOrder, name="new-order"),
    path("all-order/", views.CreateOrderAll.as_view(), name="all-order"),
    path("confirm-order/<int:id>/", views.ConfirmOrder, name="confirm-order"),
    path("order-detail/<int:id>/", views.GetOrderDetail.as_view(), name="order-detail"),
    path("delete-order-detail/<int:id>/", views.DeleteOrderDetail, name="delete-order-detail"),
    path("order-complete/<int:id>/", views.OrderComplete, name="order-complete"),
]

product/urls.py
from django.urls import path,include
from . import views

app_name = 'Product'
urlpatterns = [
    path('', views.ProductClass.as_view(), name='products'),
    path('create/', views.CreateProduct.as_view(), name='create-product'),
    path('add/', views.CreateProduct.as_view(), name='add-product'),
    path('delete/<int:id>/', views.DeleteProduct.as_view(), name='delete-product'),
    path('update/<int:id>/', views.UpdateProduct.as_view(), name='update-product'),
    path('detail/<int:id>/', views.DetailProduct.as_view(), name='detail-product'),
    path('updateProductData/<int:id>/', views.UpdateProduct.as_view(), name='update-product-post'),
    path('search/<str:name>', views.SearchProduct.as_view(), name='get-product-search'),

    path('category/<int:id>/', views.category_search, name='category_search'),
    path('category/', views.CategoryClass.as_view(), name='categoryes'),
    path('createCategory/', views.CreateCategory.as_view(), name='create-category'),
    path('addCategory/', views.CreateCategory.as_view(), name='add-category'),
    path('deleteCategory/<int:id>/', views.DeleteCategory.as_view(), name='delete-category'),
    path('updateCategory/<int:id>/', views.UpdateCategory.as_view(), name='update-category'),
    path('updateCategoryData/<int:id>/', views.UpdateCategory.as_view(), name='update-category-post'),

    path('variation/', views.VariationClass.as_view(), name='variations'),
    path('createVariation/', views.CreateVariation.as_view(), name='create-variation'),
    path('addVariation/', views.CreateVariation.as_view(), name='add-variation'),
    path('deleteVariation/<int:id>/', views.DeleteVariation.as_view(), name='delete-variation'),
    path('updateVariation/<int:id>/', views.UpdateVariation.as_view(), name='update-variation'),
    path('updateVariationData/<int:id>/', views.UpdateVariation.as_view(), name='update-variation-post'),



    path("addCart/<int:id>/", views.AddCart, name='addCart'),
    path("cart/", views.Cart, name='cart'),
    path("DeleteCart/<int:id>/", views.DeleteCart, name='delete-item-cart'),

    path('addmessage/', views.CreateMessage.as_view(), name='add_message'),

    ]

user/urls.py
from django.urls import path,include
from . import views

app_name = 'User'

urlpatterns = [
    path('', views.UserClass.as_view(), name='users'),
    path('create/', views.CreateUser.as_view(), name='create-user'),
    path('add/', views.CreateUser.as_view(), name='add-user'),
    path('delete/<int:id>/', views.DeleteUser.as_view(), name='delete-user'),
    path('update/<int:id>/', views.UpdateUser.as_view(), name='update-user'),
    path('updateProductData/<int:id>/', views.UpdateUser.as_view(), name='update-user-post'),
    path('login/', views.LoginUser.as_view(), name='login-user'),
    path('logout/', views.LogoutUser.as_view(), name='logout-user'),
]

templates/homepage/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'homepage/css/style.css' %}">
    {% block cssblock %}
    {% endblock %}

</head>
<style>
    .fixed {

        position: fixed;
        right: 50px;
        bottom: 150px;
        z-index: 1030;
        text-align: center;
    }

    .contact-item {
        margin: 5px;
        width: 50px;
        height: 50px;
        border-radius: 50px;
        color: white;
        background-color: rgba(238, 72, 12);
        display: flex;
        align-items: flex-end;
        justify-content: center;
    }
</style>

<body>
    {% include 'homepage/navbar.html' %}

    {% block content %}
    {% endblock %}

    {% include 'homepage/footer.html' %}

    {% block jsblock %}
    {% endblock %}

    <div class="fixed bg-orange">
        <div class="contact-item">
            <h2><i class="fa-solid fa-phone"></i></h2>
        </div>
        <div class="contact-item">
            <h2><i class="fa-solid fa-message"></i></h2>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous"></script>
    <script src="{% static 'homepage/js/jquery.js' %}"></script>
    <script src="{% static 'homepage/js/app.js' %}"></script>
</body>

</html>

templates/homepage/footer.html
<!-- Contact -->
<div class="mt-5"></div>
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-md fs-6 fw-normal">
        <p class="fs-5 fw-bold">Thông tin chung</p>
        <ul class="list-unstyled">
          <li>Giới thiệu về Shop</li>
          <li>Tin tuyển dụng</li>
          <li>Tin tức</li>
          <li>Tin khuyến mãi</li>
          <li>Liên hệ, góp ý</li>
          <li>Khách hàng doanh nghiệp</li>
        </ul>
      </div>
      <div class="col-md fs-6 fw-normal">
        <p class="fs-5 fw-bold">Hỗ trợ khách hàng</p>
        <ul class="list-unstyled">
          <li>Tìm hiểu về mua trả góp</li>
          <li>Chính sách vận chuyển, giao hàng</li>
          <li>Chính sách, quy định chung</li>
          <li>Chính sách bảo hành</li>
          <li>Chính sách đổi hàng</li>
          <li>Bảo mật thông tin khách hàng</li>
        </ul>
      </div>
      <div class="col-md fs-6 fw-normal">
        <p class="fs-5 fw-bold">Địa chỉ cửa hàng</p>
        <ul class="list-unstyled">
          <li>54 Nguyễn Lương Bằng, Hoà Khánh Bắc, Liên Chiểu, Đà Nẵng</li>
        </ul>
      </div>
    </div>
  </div>
</footer>>

<!-- Footer -->
<footer class="p-2 bg-dark text-white text-center position-relative">
  <div class="container">
    <p class="lead">Copyright &copy; 2021 Frontend Bootcamp</p>

    <a href="#" class="position-absolute bottom-0 end-0 p-2">
      <i class="bi bi-arrow-up-circle h1"></i>
    </a>
  </div>
</footer>

templates/homepage/index.html
{% extends 'homepage/base.html' %}
{% load static %}
{% block cssblock %}
<link rel="stylesheet" href="{% static 'homepage/css/style.css' %}">
{% endblock %}

{% block content %}
<div id="carouselExampleControls" class="carousel slide container" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active" data-interval='1'>
        <img src="{% static 'homepage/img/shop4.jpg' %}" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item" data-interval='1'>
        <img src="{% static 'homepage/img/shop5.jpg' %}" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item" data-interval='1'>
        <img src="{% static 'homepage/img/shop3.jpg' %}" class="d-block w-100" alt="...">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
{% endblock %}
{% block jsblock %}
<script src="{% static 'homepage/js/app.js' %}">
</script>
<script src="{% static 'homepage/js/jquery.js' %}">
</script>
{% endblock %}

templates/homepage/navbar.html
{% load static %}
<!-- Newsletter -->
<section class="bg-dark text-light p-3">
  <div class="container">
    <div class="d-md-flex justify-content-between align-items-center">
      <a href="{% url 'Home:home' %}" style="text-decoration: none;"><h3 class="mb-3 mb-md-0 fs-1">BCH SHOP</h3></a>
      <div class="row justify-content-center">
        {% if not user.is_authenticated %}
        <div class="col-6"><a href="{% url 'User:create-user' %}">Register</a></div>
        <div class="col-6"><a href="{% url 'User:login-user' %}">Sign in</a></div>
        {% else %}
        <div class="col-4  mx-auto"> <img style="vertical-align: middle;
            width: 50px;
            height: 50px;
            border-radius: 50%;" src="/media/{{ user.avatar }}" alt="Avatar" class="avatar"></a></div>
        <div class="col-4 "><a href="#" class="fs-5  align-middle">{{ request.user.username }}</a></div>
        <div class="col-4"><a href="{% url 'User:logout-user' %}" class="m-3"><i class="fa fa-sign-out fa-xl"
              aria-hidden="true"></i></a></div>
        {% endif %}

      </div>
    </div>
  </div>
</section>

<!-- Navbar -->
<nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3">
  <div class="container">
    {% if not checkAdmin %}
    <div class="me-5 pe-5">
      <a href="{% url 'Product:products' %}" class="navbar-brand fs-5">Product</a>
    </div>
    {% else %}
    <div class="collapse navbar-collapse me-2" id="navmenu">
      <ul class="navbar-nav ms-auto ">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle fs-5 me-5 pe-5" href="{% url 'Product:products' %}" id="navbarDropdown"
            role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Product
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'Product:products' %}">All Product</a></li>
            <li><a class="dropdown-item" href="{% url 'Product:create-product' %}">Create Product</a></li>
          </ul>
        </li>
      </ul>
    </div>
    {% endif %}
    <div class="input-group news-input m-auto position-relative" id="content">
      <input type="text" class="form-control" placeholder="Find product ..." id="cowngu" onkeyup='myFunction()' />
      <button class="btn btn-danger btn-lg" type="button">Search</button>
    </div>
    <div class="collapse navbar-collapse justify-content-end" id="navmenu">
      <ul class="navbar-nav ms-auto ">
        {% if checkAdmin %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle fs-5" href="{% url 'Product:categoryes' %}" id="navbarDropdown"
            role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Category
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'Product:categoryes' %}">All Category</a></li>
            <li><a class="dropdown-item" href="{% url 'Product:create-category' %}">Create Category</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle fs-5" href="{% url 'Product:variations' %}" id="navbarDropdown"
            role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Variation
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'Product:variations' %}">All Variation</a></li>
            <li><a class="dropdown-item" href="{% url 'Product:create-variation' %}">Create Variation</a></li>
          </ul>
        </li>
        {% else %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle fs-5" href="{% url 'Product:categoryes' %}" id="navbarDropdown"
            role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Category
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% for item in category_title %}
            <li><a class="dropdown-item" href="{% url 'Product:category_search' item.id %}">{{item.title}}</a></li>
            {% endfor %}
          </ul>
        </li>
        <li class="nav-item ms-3" style="display: flex; align-items: center;">
          <div class="cart">
            <div class="cart_container d-flex flex-row align-items-center justify-content-end">
              <a href="{% url 'Product:cart' %}"><i class="fa fa-shopping-cart fa-xl" aria-hidden="true"></i></a>
              <div class="cart_icon">
                <div class="cart_count" style="
                display: block;
                margin-bottom: 15px;"><span>{{cart}}</span></div>
              </div>
            </div>
          </div>
        </li>
        <li class="nav-item ms-3" style="display: flex; align-items: center;">
          <div class="cart">
            <div class="cart_container d-flex flex-row align-items-center justify-content-end">
              <a href="{% url 'Order:all-order' %}"><i class="fa fa-truck fa-xl" aria-hidden="true"></i></a>
              <div class="cart_icon">
                <div class="cart_count" style="
                display: block;
                margin-bottom: 15px;"><span>{{numberOrder}}</span></div>
              </div>
            </div>
          </div>
        </li>
        {% endif %}
        {% if checkAdmin %}
        <li class="nav-item ">
          <a href="{% url 'Order:all-order' %}" class="nav-link fs-5">Order</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
<!-- <div id="content"></div> -->
<div class="mt-5"></div>

<!-- Slider -->
<div class="container" style="z-index: -100;">
  <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'homepage/img/8.jpg' %}" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="{% static 'homepage/img/9.jpg' %}" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="{% static 'homepage/img/10.jpg' %}" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="{% static 'homepage/img/11.jpg' %}" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="{% static 'homepage/img/12.jpg' %}" class="d-block w-100" alt="...">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
  <div class="mb-5"></div>
</div>

<!-- <i class="fas fa-chevron-down"></i> -->