ShopBCH/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('product/', include('product.urls')),
    path('user/', include('user.urls')),
    path('order/', include('order.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from .views import HomeView
from django.urls import path
app_name = 'Home'
urlpatterns = [
    path('',HomeView.as_view(), name='home' ),
]

user/urls.py
from django.urls import path,include
from . import views

app_name = 'User'

urlpatterns = [
    path('', views.UserClass.as_view(), name='users'),
    path('create/', views.CreateUser.as_view(), name='create-user'),
    path('add/', views.CreateUser.as_view(), name='add-user'),
    path('delete/<int:id>/', views.DeleteUser.as_view(), name='delete-user'),
    path('update/<int:id>/', views.UpdateUser.as_view(), name='update-user'),
    path('updateProductData/<int:id>/', views.UpdateUser.as_view(), name='update-user-post'),
    path('login/', views.LoginUser.as_view(), name='login-user'),
    path('logout/', views.LogoutUser.as_view(), name='logout-user'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Permission
# Create your models here.

class CustomerUser(AbstractUser):
    phone_number = models.CharField(max_length=10,default="")
    address = models.CharField(default="", max_length=255)
    avatar = models.ImageField(upload_to='images',default=None,null=False)
    
    def __str__(self):
        return self.username
    class Meta:
        permissions = permissions = [('can_view_category', 'can_view_category'),
                                    ('can_change_order', 'can_change_order'),
                                    ('can_view_product', 'can_view_product'),
                                    ('can_view_variation', 'can_view_variation'),
                                    ('can_change_user', 'can_change_user'),
                                    ('can_add_order', 'can_add_order'),
                                    ('can_delete_order', 'can_delete_order'),
                                    ('can_view_order', 'can_view_order'),
                                    ('can_add_cart', 'can_add_cart'),
                                    ('can_change_cart', 'can_change_cart'),
                                    ('can_delete_cart', 'can_delete_cart'),
                                    ('can_view_cart', 'can_view_cart'),
                                    ('can_add_cart_item', 'can_add_cart_item'),
                                    ('can_change_cart_item', 'can_change_cart_item'),
                                    ('can_delete_cart_item', 'can_delete_cart_item'),
                                    ('can_view_cart_item', 'can_view_cart_item'),
                                    
                                    ('can_add_message', 'can_add_message'),
                                    ('can_change_message', 'can_change_message'),
                                    ('can_delete_message', 'can_delete_message'),
                                    ('can_view_message', 'can_view_message'),
                                    ('can_add_order_detail', 'can_add_order_detail'),
                                    ('can_change_order_detail', 'can_change_order_detail'),
                                    ('can_delete_order_detail', 'can_delete_order_detail'),
                                    ('can_view_order_detail', 'can_view_order_detail')]

user/forms.py
from django import forms
from .models import CustomerUser

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = CustomerUser
        fields = ('username', 'password', 'email', 'phone_number', 'address', 'avatar')
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-control'})
        self.fields['password'].widget.attrs.update({'class': 'form-control'})
        self.fields['email'].widget.attrs.update({'class': 'form-check-input'})
        self.fields['phone_number'].widget.attrs.update({'class': 'form-control'})
        self.fields['address'].widget.attrs.update({'class': 'form-control'})
        self.fields['avatar'].widget.attrs.update({'class': 'form-control'})

class AdminForm(forms.ModelForm):
    class Meta:
        model = CustomerUser
        fields = ('username', 'password')

user/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.views import View
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import Group, Permission
from .models import CustomerUser
from product.models import Product
from .forms import UserForm
# Create your views here.
class UserClass(LoginRequiredMixin ,View):
    login_url = '/user/login/'
    redirect_field_name = 'login-user'
    def get(self, request):
        if request.user.has_perm("user.view_user"):
            qs = CustomerUser.objects.all()
            return render(request, 'user/index.html', {'users': qs})
        else:
            qs = Product.objects.all()
            checkAdmin = request.user.is_superuser
            return redirect('/product/')
        # return render(request, 'user/login.html')


class CreateUser(View):
    def get(self, request):
        userForm = UserForm()
        return render(request, "user/create.html", {'userForm':userForm})
    def post(self, request):
        username =  request.POST.get('username')
        password = request.POST.get('password')
        avatar = request.FILES['avatar']
        # group = Group.objects.get(name = 'User')
        if avatar is None:
            avatar = "avatar.png"
        user = CustomerUser.objects.create(username=username, avatar=avatar)
        user.set_password(password)
        # user.groups.add(group)
        user.save()
        return redirect('/user/')

class DeleteUser(LoginRequiredMixin, View):
    login_url = '/user/login/'
    redirect_field_name = 'login-user'
    def post(self,request, id):
        if request.user.is_authenticated():
            user = CustomerUser.objects.get(id=id)
            user.delete()
            return redirect('/user/')

class UpdateUser(LoginRequiredMixin, View):
    login_url = '/user/login/'
    redirect_field_name = 'login-user'
    def get(self,request,id):
        user = CustomerUser.objects.get(id=id)
        f = UserForm(instance=user)
        return render(request, 'user/update.html', {'userForm': f,'user':user})
    def post(self,request,id):
        user = CustomerUser.objects.get(id=id)
        f = UserForm(request.POST, request.FILES ,instance=user)
        if f.is_valid():
            f.save()
            return redirect('/user/')           
        return HttpResponse('Invalid data update')     


class LoginUser(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return render(request, 'user/login.html')
    def post(self, request):
        username =  request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password) 
        
        if user is not None:
            login(request, user)
            return redirect('/product/')
        else:      

            return render(request, 'user/login.html', {'error': "Tài khoản hoặc mật khẩu không chính xác !"})
class LogoutUser(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect('/product/')

user/templates/user/create.html
<!doctype html>
<html lang="en">
    {% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Register</title>
    <script src="https://kit.fontawesome.com/28725eb711.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'user/style.css' %}">
</head>
  <body style="margin:0;padding:0; overflow:hidden;">
    <div class="row p-5">
        <div class="col-3">
        </div>
        <div class="col-6">
            <div class="text-center">
                <h4 class="text-primary">Đăng ký</h4>
            </div>
            <form class ="p-5" action ="{% url 'User:add-user' %}"  method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <!-- Email input -->
                <div class="form-outline mb-4">
                    <label class="form-label" for="form2Example1">Username</label>
                    <br>
                    {{userForm.username}}
                </div>
              
                <!-- Password input -->
                <div class="form-outline mb-4">
                  <label class="form-label" for="form2Example2">Password</label>
                  <br>
                  {{userForm.password}}
                </div>
                
                <div class="form-outline mb-4">
                    <label class="form-label" for="form2Example2">Avatar</label>
                    {{userForm.avatar}}
                </div>
               
                <!-- Submit button -->
                <div class="text-center">

                    <button type="submit" class="btn btn-primary btn-block mb-4">Register</button>
                 
                </div>
                
                <!-- Register buttons -->
                <div class="text-center">
                  <button type="button" class="btn btn-link btn-floating mx-1">
                    <i class="fab fa-facebook-f"></i>
                  </button>
              
                  <button type="button" class="btn btn-link btn-floating mx-1">
                    <i class="fab fa-google"></i>
                  </button>
              
                  <button type="button" class="btn btn-link btn-floating mx-1">
                    <i class="fab fa-twitter"></i>
                  </button>
              
                  <button type="button" class="btn btn-link btn-floating mx-1">
                    <i class="fab fa-github"></i>
                  </button>
                </div>
              </form>
        </div>
        <div class="col-3"></div>
    </div>
    
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>

user/templates/user/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <button><a href="{% url 'User:create-user' %}">Create User</a></button>
    <button><a href="{% url 'User:login-user' %}">Login User</a></button>
    <button><a href="{% url 'User:logout-user' %}">Logout User</a></button>
    {% for item in users %}
            <h1>{{item.id}}</h1>
            <p>{{item.username}}</p>
            <form action="{% url 'User:delete-user' item.id %}" method="POST">
                {% csrf_token %}
                <input name="delete" type="submit" value="Delete" />
            </form>
            <button><a href="{% url 'User:update-user' item.id %}">update</a></button>
            <p>{{item.phone_number}}</p>
            <p>{{item.address}}</p>

            <img src="/media/{{ item.avatar }}" alt="...">
    {% endfor %}
</body>
</html>

user/templates/user/login.html
<!doctype html>
<html lang="en">
    {% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login</title>
    <script src="https://kit.fontawesome.com/28725eb711.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'user/style.css' %}">
</head>
  <body style="margin:0;padding:0; overflow:hidden;">
    <div class="row p-5">
        <div class="col-3">
        </div>
        <div class="col-6">
            <div class="text-center">
                <h4 class="text-primary">Đăng nhập</h4>
            </div>
            
            <form class ="p-5" action ="{% url 'User:login-user' %}"  method="POST">
                {% csrf_token %}
                <!-- Email input -->
                <p style="text-align:center; color: red;">{{error}}</p>
                <div class="form-outline mb-4">
                    <label class="form-label" for="form2Example1">Username</label>
                  <input type="text" id="form2Example1" class="form-control" name="username" placeholder="Enter username"/>
                  
                </div>
              
                <!-- Password input -->
                <div class="form-outline mb-4">
                  <label class="form-label" for="form2Example2">Password</label>
                  <input type="password" id="form2Example2" class="form-control" name='password' placeholder="Enter password"/>
                </div>
              
                <!-- 2 column grid layout for inline styling -->
                <div class="row mb-4">
                  <div class="col d-flex justify-content-center">
                    <!-- Checkbox -->
                    <div class="form-check">
                      <input class="form-check-input" type="checkbox" value="" id="form2Example31" checked />
                      <label class="form-check-label" for="form2Example31"> Remember me </label>
                    </div>
                  </div>
              
                  <div class="col">
                    <!-- Simple link -->
                    <a href="#!">Forgot password?</a>
                  </div>
                </div>
                <!-- Submit button -->
                <div class="text-center">
                    <a href="{% url 'User:login-user' %}" target="_blank">
                        <button type="submit" class="btn btn-primary btn-block mb-4">Sign in</button>
                    </a>
                </div>
                
                <!-- Register buttons -->
                <div class="text-center">
                  <p>Not a member? <a href="{% url 'User:create-user' %}">Register</a></p>
                  <button type="button" class="btn btn-link btn-floating mx-1">
                    <i class="fab fa-facebook-f"></i>
                  </button>
              
                  <button type="button" class="btn btn-link btn-floating mx-1">
                    <i class="fab fa-google"></i>
                  </button>
              
                  <button type="button" class="btn btn-link btn-floating mx-1">
                    <i class="fab fa-twitter"></i>
                  </button>
              
                  <button type="button" class="btn btn-link btn-floating mx-1">
                    <i class="fab fa-github"></i>
                  </button>
                </div>
              </form>
        </div>
        <div class="col-3"></div>
    </div>
    
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>

user/templates/user/update.html
<form action ="{% url 'User:update-user-post' user.id %}" method = "post" enctype="multipart/form-data">
    {% csrf_token %}
    <p> <label>Username: </label> {{userForm.username}}</p>
    <p> <label>Email: </label> {{userForm.email}}</p>
    <p> <label>Phonenumber: </label> {{userForm.phone_number}}</p>
    <p> <label>Address: </label> {{userForm.address}}</p>
    <p> <label>Avatar: </label> {{userForm.avatar}}</p>
    <input type="submit" value=Update>
</form>