ShopBCH/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('product/', include('product.urls')),
    path('user/', include('user.urls')),
    path('order/', include('order.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from .views import HomeView
from django.urls import path
app_name = 'Home'
urlpatterns = [
    path('',HomeView.as_view(), name='home' ),
]

order/urls.py
from django.urls import path,include
from . import views

app_name = 'Order'
urlpatterns =[
    path("new-order/", views.CreateOrder, name="new-order"),
    path("all-order/", views.CreateOrderAll.as_view(), name="all-order"),
    path("confirm-order/<int:id>/", views.ConfirmOrder, name="confirm-order"),
    path("order-detail/<int:id>/", views.GetOrderDetail.as_view(), name="order-detail"),
    path("delete-order-detail/<int:id>/", views.DeleteOrderDetail, name="delete-order-detail"),
    path("order-complete/<int:id>/", views.OrderComplete, name="order-complete"),
]

product/urls.py
from django.urls import path,include
from . import views

app_name = 'Product'
urlpatterns = [
    path('', views.ProductClass.as_view(), name='products'),
    path('create/', views.CreateProduct.as_view(), name='create-product'),
    path('add/', views.CreateProduct.as_view(), name='add-product'),
    path('delete/<int:id>/', views.DeleteProduct.as_view(), name='delete-product'),
    path('update/<int:id>/', views.UpdateProduct.as_view(), name='update-product'),
    path('detail/<int:id>/', views.DetailProduct.as_view(), name='detail-product'),
    path('updateProductData/<int:id>/', views.UpdateProduct.as_view(), name='update-product-post'),
    path('search/<str:name>', views.SearchProduct.as_view(), name='get-product-search'),

    path('category/<int:id>/', views.category_search, name='category_search'),
    path('category/', views.CategoryClass.as_view(), name='categoryes'),
    path('createCategory/', views.CreateCategory.as_view(), name='create-category'),
    path('addCategory/', views.CreateCategory.as_view(), name='add-category'),
    path('deleteCategory/<int:id>/', views.DeleteCategory.as_view(), name='delete-category'),
    path('updateCategory/<int:id>/', views.UpdateCategory.as_view(), name='update-category'),
    path('updateCategoryData/<int:id>/', views.UpdateCategory.as_view(), name='update-category-post'),

    path('variation/', views.VariationClass.as_view(), name='variations'),
    path('createVariation/', views.CreateVariation.as_view(), name='create-variation'),
    path('addVariation/', views.CreateVariation.as_view(), name='add-variation'),
    path('deleteVariation/<int:id>/', views.DeleteVariation.as_view(), name='delete-variation'),
    path('updateVariation/<int:id>/', views.UpdateVariation.as_view(), name='update-variation'),
    path('updateVariationData/<int:id>/', views.UpdateVariation.as_view(), name='update-variation-post'),



    path("addCart/<int:id>/", views.AddCart, name='addCart'),
    path("cart/", views.Cart, name='cart'),
    path("DeleteCart/<int:id>/", views.DeleteCart, name='delete-item-cart'),

    path('addmessage/', views.CreateMessage.as_view(), name='add_message'),

    ]

cart/models.py
from django.db import models
from product.models import Variation
from user.models import CustomerUser

# Create your models here.
class Cart(models.Model):
    user = models.ForeignKey(CustomerUser,on_delete=models.CASCADE)
    number = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now = True)

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    item = models.ForeignKey(Variation, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)

product/forms.py
from unicodedata import category
from django import forms
from .models import Product, Category, Variation

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        widget ={
                category:= forms.ModelChoiceField(
                    queryset=Category.objects.all(), 
                    label="Category",
                    widget=forms.Select(
                                attrs={
                                    'placeholder': 'Product Category', 'class': 'form-control'}),
                                required=True
                    )
        }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'form-control'})
        self.fields['description'].widget.attrs.update({'class': 'form-control'})
        # self.fields['category'].widget.attrs.update({'style': 'width:100px !important;'})
        self.fields['category'].widget.attrs['style'] = 'width:100px !important;'
        self.fields['price'].widget.attrs.update({'class': 'form-control'})
        self.fields['active'].widget.attrs.update({'class': 'form-check-input'})
        self.fields['product_img'].widget.attrs.update({'class': 'form-control'})
        self.fields['image_view'].widget.attrs.update({'class': 'form-control'})

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'
        widget ={
                category:= forms.ModelChoiceField(
                    queryset=Category.objects.all(), 
                    label="Category",
                    widget=forms.Select(
                                attrs={
                                    'placeholder': 'Product Category', 'class': 'form-control'}),
                                required=True
                    )
        }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'form-control'})
        self.fields['slug'].widget.attrs.update({'class': 'form-control'})
        self.fields['description'].widget.attrs.update({'class': 'form-control'})
        self.fields['active'].widget.attrs.update({'class': 'form-check-input'})

class VariationFrom(forms.ModelForm):
    class Meta:
        model = Variation
        fields = '__all__'
        widget ={
                category:= forms.ModelChoiceField(
                    queryset=Variation.objects.all(), 
                    label="Variation",
                    widget=forms.Select(
                                attrs={
                                    'placeholder': 'Product Category', 'class': 'form-control'}),
                                required=True
                    )
        }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'form-control'})
        self.fields['product'].widget.attrs.update({'class': 'product'})
        self.fields['price'].widget.attrs.update({'class': 'form-control'})
        self.fields['active'].widget.attrs.update({'class': 'form-check-input'})
        self.fields['sale_price'].widget.attrs.update({'class': 'form-control'})
        self.fields['inventory'].widget.attrs.update({'class': 'form-control'})

cart/views.py
from django.shortcuts import render

# Create your views here.

product/views.py
import re
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views import View
from numpy import product

from user.models import CustomerUser
from .serializers import ProductSerializer
from .forms import ProductForm, CategoryForm, VariationFrom
from .models import Product, Category, Variation, Message
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from order.models import Order, OrderDetail

class ProductClass(View):
    def get(self, request):
        numberOrder = 0
        if request.user.is_authenticated:
            iduser = request.user.id
            numberOrder = Order.objects.filter(user=iduser, is_completed = False).count()
        if 'cart' not in request.session:
            request.session['cart'] = {}
        qs1 = Category.objects.values("id", "title")
        qs = Product.objects.all()
        checkAdmin = request.user.is_superuser
        return render(request, 'product/index.html', {'numberOrder': numberOrder,'products': qs,'category_title': qs1, 'checkAdmin': checkAdmin, "cart": len(request.session['cart'])})

class CreateProduct(View):
    def get(self, request):
        productForm = ProductForm()
        checkAdmin = request.user.is_superuser
        if request.user.has_perm("product.add_product"):
            return render(request, "product/create.html", {'productForm':productForm, 'checkAdmin': checkAdmin})
    def post(self, request):
        product = ProductForm(request.POST, request.FILES)
        if request.user.is_authenticated:
            if request.user.has_perm("product.add_product"):
                if product.is_valid():
                    product.save()
                    return redirect('/product/')
                else:
                    return HttpResponse('Invalid data input')


class DeleteProduct(View):
    def post(self,request, id):
        product = Product.objects.get(id=id)
        product.delete()
        return redirect('/product/')

class UpdateProduct(View):
    def get(self,request,id):
        product = Product.objects.get(id=id)
        checkAdmin = request.user.is_superuser
        f = ProductForm(instance=product)
        return render(request, 'product/update.html', {'productForm': f,'product':product, 'checkAdmin': checkAdmin})
    def post(self,request,id):
        product = Product.objects.get(id=id)
        f =ProductForm(request.POST, request.FILES,instance=product)
        if f.is_valid():
            f.save()
            return redirect('/product/')           
        return HttpResponse('Invalid data update')

class DetailProduct(View):
    def get(self,request,id):
        if 'cart' not in request.session:
            request.session['cart'] = {}
        numberOrder = 0
        if request.user.is_authenticated:
            iduser = request.user.id
            numberOrder = Order.objects.filter(user=iduser, is_completed = False).count()
        product = Product.objects.get(id=id)
        messages = Message.objects.filter(product=product)
        qs1 = Category.objects.values("id", "title")
        checkAdmin = request.user.is_superuser
        if request.user.username:
            avatar = CustomerUser.objects.get(username=request.user.username).avatar.url            
        else:
            avatar = 'aaa'
        return render(request, 'product/detail.html', {'numberOrder': numberOrder,'product':product, 'cart': len(request.session['cart']), 'category_title': qs1, 'checkAdmin': checkAdmin, 'messages': messages, 'avatar': avatar})

def category_search(request, id):
    if 'cart' not in request.session:
            request.session['cart'] = {}
    numberOrder = 0
    if request.user.is_authenticated:
        iduser = request.user.id
        numberOrder = Order.objects.filter(user=iduser, is_completed = False).count()
    product = Product.objects.filter(category = id)
    qs1 = Category.objects.values("id", "title")
    checkAdmin = request.user.is_superuser
    return render(request, 'product/index.html', {'numberOrder': numberOrder,'products': product, "cart": len(request.session['cart']), 'category_title': qs1, 'checkAdmin': checkAdmin})

class CategoryClass(View):
    def get(self, request):
        if 'cart' not in request.session:
            request.session['cart'] = {}
        numberOrder = 0
        if request.user.is_authenticated:
            id = request.user.id
            numberOrder = Order.objects.filter(user=id, is_completed = False).count()
        qs = Category.objects.all()
        qs1 = Category.objects.values("id", "title")
        checkAdmin = request.user.is_superuser
        return render(request, 'category/index.html', {'numberOrder': numberOrder,'categoryes': qs, "cart": len(request.session['cart']), 'category_title':qs1, 'checkAdmin': checkAdmin})
class CreateCategory(View):
    def get(self, request):
        categoryForm = CategoryForm()
        checkAdmin = request.user.is_superuser
        return render(request, "category/create.html", {'categoryForm':categoryForm, 'checkAdmin': checkAdmin})
    def post(self, request):
        category = CategoryForm(request.POST)
        if category.is_valid():
            category.save()
            return redirect('/product/category/')
        else:
            return HttpResponse('Invalid data input')

class DeleteCategory(View):
    def get(self,request, id):
        category = Category.objects.get(id=id)
        category.delete()
        return redirect('/product/category/')
class UpdateCategory(View):
    def get(self,request,id):
        category = Category.objects.get(id=id)
        f = CategoryForm(instance=category)
        checkAdmin = request.user.is_superuser
        return render(request, 'category/update.html', {'categoryForm': f,'category':category, 'checkAdmin': checkAdmin})
    def post(self,request,id):
        category = Category.objects.get(id=id)
        f = CategoryForm(request.POST,instance=category)
        if f.is_valid():
            f.save()
            return redirect('/product/category/')           
        return HttpResponse('Invalid data update')





class VariationClass(View):
    def get(self, request):
        varis = Variation.objects.all()
        checkAdmin = request.user.is_superuser
        return render(request, 'variation/index.html', {'variations': varis, 'checkAdmin': checkAdmin})

class CreateVariation(View):
    def get(self, request):
        checkAdmin = request.user.is_superuser
        variationForm = VariationFrom()
        return render(request, "variation/create.html", {'variation':variationForm, 'checkAdmin': checkAdmin})
    def post(self, request):
        variation = VariationFrom(request.POST)
        if variation.is_valid():
            variation.save()
            return redirect('/product/variation/')
        else:
            return HttpResponse('Invalid data input')

class DeleteVariation(View):
    def get(self, request, id):
        varia = Variation.objects.get(id=id)
        varia.delete()
        return redirect('/product/variation/')

class UpdateVariation(View):
    def get(self,request,id):
        varia = Variation.objects.get(id=id)
        form = VariationFrom(instance=varia)
        return render(request, 'variation/update.html', {'variationForm': form, 'variation': varia})
    def post(self,request,id):
        variation = Variation.objects.get(id=id)
        form = VariationFrom(request.POST,instance=variation)
        if form.is_valid():
            form.save()
            return redirect('/product/variation/')           
        return HttpResponse('Invalid data update')


def AddCart(request, id):
    id = str(id)
    product = Product.objects.get(id=id)
    if id in request.session['cart'].keys():
        itemCart = {
            "id": id, 
            "name": product.title,
            "price": product.price,
            "image": product.image_view.url,
            "number" : int(request.session['cart'][id]['number'] + 1),
            "total": float(product.price * int(request.session['cart'][id]['number'] + 1) ),
            
        }
    else:
        itemCart = {
            "id" : id,
            "name": product.title,
            "price": product.price,
            "image": product.image_view.url,
            "total": product.price,
            "number" : 1
        }
    request.session['cart'][id] = itemCart
    request.session.modified = True
    return redirect('/product/')

from order.forms import OrderForm
def Cart(request):
    form = OrderForm()
    qs1 = Category.objects.values("id", "title")
    if 'cart' not in request.session:
        request.session['cart'] = {}
    numberOrder = 0
    if request.user.is_authenticated:
        id = request.user.id
        numberOrder = Order.objects.filter(user=id, is_completed = False).count()
    return render(request, 'product/cart.html', {'numberOrder':numberOrder, 'cartInfo':request.session['cart'],'category_title':qs1, 'cart': len(request.session['cart']), "form":form})
def DeleteCart(request, id):
    id=str(id)
    request.session['cart'].pop(id)
    request.session.modified = True
    return redirect('/product/cart/')

class SearchProduct(View):
    def get(self, request, name):
        qs = Product.objects.filter(title__icontains=name)
        data = ProductSerializer(qs, many=True)
        return JsonResponse(data.data, safe=False, status=200)

class CreateMessage(View):
    def post(self, request):
        id_product = request.POST.get('id_product')
        id_user = request.user.id
        message = request.POST.get('message')
        product = Product.objects.get(id=id_product)
        user = CustomerUser.objects.get(id=id_user)
        Message.objects.create(product=product, user=user, message=message)
        return redirect('/product/detail/'+str(id_product)+'/')

product/templates/product/cart.html
{% extends "homepage/base.html" %}

{% load static %}
{% block cssblock %}
<link rel="stylesheet" href="{% static 'product/style.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="d-flex justify-content-center row">
        <div class="col-md-12">
            <div class="rounded">
                <div class="table-responsive table-borderless">
                    {% if cart > 0 %}
                    <h2 class="text-center">YOUR CART</h2>
                    <table class="table text-center">
                        <thead>
                            <tr>
                                <th>Name Product</th>
                                <th>Image</th>
                                <th>Number</th>
                                <th>Price</th>
                                <th>Total</th>
                                <th>Option</th>
                            </tr>
                        </thead>
                        <tbody class="table-body" >
                            {% for key, value in cartInfo.items %}
                                <tr class="cell-1 ">
                                    <td>{{ value.name }}</td>
                                    <td><img src="{{ value.image }}" class="rounded float-left img-cart" alt="..."></td>
                                    
                                    <td>{{ value.number }}</td>
                                    <td>{{ value.price }}</td>
                                    <td>{{ value.total }}</td>
                                    <td>
                                        <a href="{% url 'Product:delete-item-cart' value.id %}">
                                            <button type="button" class="btn btn-danger">Delete</button>
                                        </a>
                                </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <button type="button" onclick="fillInfo()" class="btn btn-outline-primary m-2">
                        Purchase confirmation
                        </button>
                    {% else %}
                        <div class="card">
                        <div class="card-body cart">
                                <div class="col-sm-12 empty-cart-cls text-center">
                                    <img src="https://i.imgur.com/dCdflKN.png" width="130" height="130" class="img-fluid mb-4 mr-3">
                                    <h3><strong>Your Cart is Empty</strong></h3>
                                    <h4>Add something to make me happy :)</h4>
                                    <a href="{% url 'Product:products' %}" class="btn btn-primary cart-btn-transform m-3" data-abc="true">Continue shopping</a>
                                </div>
                        </div>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div id="Info" class="container-fluid" style="display: none;">
        <form action="{% url 'Order:new-order' %}" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col">
                    <label>Recipient's name</label>
                  <input type="text" class="form-control" placeholder="Recipient's name" name="name_receive" required>
                </div>
                <div class="col">
                    <label>Phone number</label>
                  <input type="text" class="form-control" placeholder="Phone number" name="phone_number" required>
                  
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <label>Receiving address</label>
                  <input type="text" class="form-control" placeholder="Receiving address" name="address_receive" required>
                  
                </div>
                <div class="col">
                    <label>Description</label>
                  <input type="textarea" class="form-control" placeholder="Description" name="description" required>
                  
                </div>
            </div>
            <button type="submit" class="btn btn-primary mt-3">Order</button>
          </form>
    </div>
</div>
<script> 
    function fillInfo(){ 
    document.getElementById('Info').style.display = 'block';
}
</script>
{% endblock %}

product/templates/product/detail.html
{% extends "homepage/base.html" %}
{% load static %}


{% block cssblock %}
<link rel="stylesheet" href="{% static 'product/style.css' %}">
{% endblock %}


{% block content %}

<div class="container">
    <div class="mb-2">
        <h4 class="p-2">{{ product.title }}</h4>
        <span class="px-2"></span>(0) lượt đánh giá)</span>
        <span class="px-5">Tình trạng: {% if product.active %} Còn hàng {% else %} Hết hàng {% endif %}</span>
        <span class="">Bảo hành: 12 Tháng</span>
    </div>
    <div class="mb-2 line-bottom"></div>
    <div class="card">
        <div class="row">
            <div class="col-4" style="display: flex;
            justify-content: space-evenly;
            flex-direction: column;">
                <img src="/media/{{ product.image_view }}" style="width:100%; object-fit: contain;" />
                <div class="container">
                    {{ product.description }}
                </div>
            </div>
            <div class="col mx-4">
                <div class="p-2">
                    <div>
                        <h6 class="p-3 bg-success text-white">Khuyến mãi - Quà tặng</h6>
                        <ul>
                            <li>Balo laptop hoặc túi xách Laptop trị giá 350.000</li>
                            <li>Đến tản nhiệt có quạt làm mát Laptop N192 trị giá 190.000</li>
                            <li>Chuột không dây trị giá 170.000 </li>
                            <li>Bộ dụng cụ vệ sinh laptop trị giá 50.000 </li>
                            <li>Tấm lót chuột cao cấp P03 </li>
                            <li>Giảm 10% khi mua phụ kiện kèm theo như: túi chống sốc, túi xách, ba lô, quạt tản nhiệt
                                laptop, bàn phím, chuột, tai nghe, các loại đầu chuyển, cáp chuyển. Mức giảm tối đa
                                200.000/1 sản phẩm </li>
                            <li>Trả góp lãi suất 0% áp dụng cho thẻ tín dụng Sacombank, VPbank. Trả góp lãi suất ưu đãi
                                áp dụng cho nhà tài chính HD Saison và ACS. Trả góp lãi suất uư đãi thông qua cổng MPOS
                                áp dụng cho thẻ tín dụng: Citibank, Eximbank, HSBC, MSB, Techcombank, Nam Á, Shinhan
                                bank, TP bank, Seabank, Kiên Long bank, OCB, VIB, ACB, MB, Vietcombank, SHB...</li>
                        </ul>
                    </div>
                    <div class="d-flex justify-content-center mb-3">
                        <h3 id="price-product">{{ product.price}} VNĐ</h3>
                    </div>

                    {% if not checkAdmin %}
                    <div class="d-flex justify-content-center">
                        <a href="{% url 'Product:addCart' product.id %}" class="link-div m-1">
                            <div class="card-delete">
                                <button type="submit" class="btn btn-success">Buy Now</button>
                            </div>
                        </a>
                        <a href="{% url 'Product:addCart' product.id %}" class="link-div m-1">
                            <div class="card-delete">
                                <button type="submit" class="btn btn-danger">Add to cart</button>
                            </div>
                        </a>
                    </div>
                    {% endif %}

                </div>
            </div>
            <div class="col p-3">
                <div>
                    <ul>
                        <h4>Trợ giúp:</h4>
                        <li><a href="#" target="_blank">Hướng dẫn mua hàng nhanh chóng</a></li>
                        <li><a href="#" target="_blank">Chính sách bảo hành</a></li>
                        <li><a href="#" target="_blank">Chính sách đổi hàng</a></li>
                    </ul>
                    <ul>
                        <h4>Điện thoại tư vấn - đặt hàng:</h4>
                        <li>Phan Văn Bình - 0935 81 87 31</li>
                        <li>Nguyễn Thanh Cơ - 0903 555 310</li>
                        <li>Lê Văn Huy - 0932 678 771</li>
                    </ul>
                    <ul>

                        <h4>Địa chỉ mua hàng:</h4>
                        <li>54 Nguyễn Lương Bằng, Hoà Khánh Bắc, Liên Chiểu, Đà Nẵng</li>
                    </ul>
                    <iframe
                        src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3780.5580573595416!2d108.21084147865716!3d16.061009620781476!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x314218d68dff9545%3A0x714561e9f3a7292c!2zVHLGsOG7nW5nIMSQ4bqhaSBo4buNYyBCw6FjaCBLaG9hIC0gxJDhuqFpIGjhu41jIMSQw6AgTuG6tW5n!5e0!3m2!1svi!2sus!4v1652886590405!5m2!1svi!2sus"
                        width="100%" height="200" frameborder="0" style="border:0" allowfullscreen></iframe>
                </div>
            </div>
        </div>

    </div>
</div>

<section style="background-color: #b2b2b2; border-radius: 1rem;" class="container">
    <form action="{% url 'Product:add_message' %}" method="POST" class="py-5 d-flex justify-content-center">
        {% csrf_token %}
        <div class="input-group mb-3">
            <input type="hidden" name="id_product" value="{{product.id}}" />
            <input type="text" class="form-control" placeholder="Type comment..." aria-label="Recipient's username"
                aria-describedby="button-addon2" name="message">
            <button type="submit" class="btn btn-success" id="chat-message-submit">Comment</button>
        </div>
    </form>

    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-md-12 col-lg-10">
                <div class="card text-dark">
                    <div class="card-body p-4">
                        <h4 class="mb-0">Recent comments</h4>
                        <p class="fw-light mb-4 pb-2">Latest Comments section by users</p>
                    </div>
                    <hr class="my-0" />
                </div>
                <div class="card text-dark" id="chat-messages">

                    {% for message in messages %}
                    <div class="card-body p-4">
                        <div class="d-flex flex-start">
                            <img class="rounded-circle shadow-1-strong me-3" src="/media/{{ message.user.avatar }}"
                                alt="avatar" width="60" height="60" />
                            <div>
                                <h6 class="fw-bold mb-1">{{ message.user.username }}</h6>
                                <div class="d-flex align-items-center mb-3">
                                    <p class="mb-0">
                                        {{ message.date_added }}
                                        <span class="badge bg-success">Feedback</span>
                                    </p>
                                </div>
                                <p class="mb-0">
                                    {{ message.message }}
                                </p>
                            </div>
                        </div>
                    </div>
                    <hr class="my-0" />
                    {%endfor %}
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

product/templates/product/index.html
{% extends "homepage/base.html" %}
{% load static %}


{% block cssblock %}
<link rel="stylesheet" href="{% static 'product/style.css' %}">
{% endblock %}


{% block content %}

<div class="items-product container">
    <div class="row row-cols-1 row-cols-md-4 g-4">
        {% for item in products %}
        <div class="col block-item">
            <div class="card">
                <a href="{% url 'Product:detail-product' item.id %}" class="link-div">
                    <img src="/media/{{ item.image_view }}" class="card-img-top" alt="...">
                </a>
                <div class="card-body">
                    <a href="{% url 'Product:detail-product' item.id %}" class="link-div text-decoration-none">
                        <h5 class="card-title">Tên sản phẩm: {{ item.title }}</h5>
                        <p class="card-text">{{ item.description }}</p>
                        <h5 class="card-price text-center price-product">{{ item.price }} VNĐ</h5>
                    </a>
                    <div class="card-btn d-flex justify-content-center">
                        {% if checkAdmin %}
                        <div class="card-update">
                            <a href="{% url 'Product:update-product' item.id %}">
                                <button type="button" class="btn btn-primary m-2">Update
                                </button>
                            </a>
                        </div>
                        <div class="card-delete">
                            <form action="{% url 'Product:delete-product' item.id %}" method="POST">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger m-2">Delete</button>
                            </form>
                        </div>
                        {% else %}
                        <form action="{% url 'Product:addCart' item.id %}" method="post">
                            {% csrf_token %}
                            <div class="card-delete">
                                <button type="submit" class="btn btn-info">Thêm vào giỏ</button>
                            </div>
                        </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}
{% block jsblock %}
<script src="{% static 'product/app.js' %}">
</script>
{% endblock %}