ShopBCH/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('product/', include('product.urls')),
    path('user/', include('user.urls')),
    path('order/', include('order.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from .views import HomeView
from django.urls import path
app_name = 'Home'
urlpatterns = [
    path('',HomeView.as_view(), name='home' ),
]

order/urls.py
from django.urls import path,include
from . import views

app_name = 'Order'
urlpatterns =[
    path("new-order/", views.CreateOrder, name="new-order"),
    path("all-order/", views.CreateOrderAll.as_view(), name="all-order"),
    path("confirm-order/<int:id>/", views.ConfirmOrder, name="confirm-order"),
    path("order-detail/<int:id>/", views.GetOrderDetail.as_view(), name="order-detail"),
    path("delete-order-detail/<int:id>/", views.DeleteOrderDetail, name="delete-order-detail"),
    path("order-complete/<int:id>/", views.OrderComplete, name="order-complete"),
]

product/urls.py
from django.urls import path,include
from . import views

app_name = 'Product'
urlpatterns = [
    path('', views.ProductClass.as_view(), name='products'),
    path('create/', views.CreateProduct.as_view(), name='create-product'),
    path('add/', views.CreateProduct.as_view(), name='add-product'),
    path('delete/<int:id>/', views.DeleteProduct.as_view(), name='delete-product'),
    path('update/<int:id>/', views.UpdateProduct.as_view(), name='update-product'),
    path('detail/<int:id>/', views.DetailProduct.as_view(), name='detail-product'),
    path('updateProductData/<int:id>/', views.UpdateProduct.as_view(), name='update-product-post'),
    path('search/<str:name>', views.SearchProduct.as_view(), name='get-product-search'),

    path('category/<int:id>/', views.category_search, name='category_search'),
    path('category/', views.CategoryClass.as_view(), name='categoryes'),
    path('createCategory/', views.CreateCategory.as_view(), name='create-category'),
    path('addCategory/', views.CreateCategory.as_view(), name='add-category'),
    path('deleteCategory/<int:id>/', views.DeleteCategory.as_view(), name='delete-category'),
    path('updateCategory/<int:id>/', views.UpdateCategory.as_view(), name='update-category'),
    path('updateCategoryData/<int:id>/', views.UpdateCategory.as_view(), name='update-category-post'),

    path('variation/', views.VariationClass.as_view(), name='variations'),
    path('createVariation/', views.CreateVariation.as_view(), name='create-variation'),
    path('addVariation/', views.CreateVariation.as_view(), name='add-variation'),
    path('deleteVariation/<int:id>/', views.DeleteVariation.as_view(), name='delete-variation'),
    path('updateVariation/<int:id>/', views.UpdateVariation.as_view(), name='update-variation'),
    path('updateVariationData/<int:id>/', views.UpdateVariation.as_view(), name='update-variation-post'),



    path("addCart/<int:id>/", views.AddCart, name='addCart'),
    path("cart/", views.Cart, name='cart'),
    path("DeleteCart/<int:id>/", views.DeleteCart, name='delete-item-cart'),

    path('addmessage/', views.CreateMessage.as_view(), name='add_message'),

    ]

order/models.py
from pyexpat import model
from django.db import models
from  user.models import CustomerUser
from product.models import Product
from cart.models import Cart
# Create your models here.
class Order(models.Model):
    user = models.IntegerField(null = False)
    phone_number = models.CharField(max_length=10,default="")
    name_receive = models.CharField(default="", max_length=255)
    shipping_address = models.CharField(max_length=255, default='', null=False)
    total_price = models.FloatField(default=0)
    order_description = models.TextField(default='', null=False)
    is_delivered = models.BooleanField(default=False)
    is_completed = models.BooleanField(default=False)
    def __str__(self):
        return self.phone_number

class OrderDetail(models.Model):
    order_id = models.IntegerField(null = False)
    pro_name = models.CharField(max_length=255)
    money = models.IntegerField(null = False, default=0)
    amount = models.IntegerField(default=1, null=False)
    total_money = models.FloatField(default=0)
    address_delivery = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)

order/forms.py
from pyexpat import model
from django import forms
from numpy import product
from .models import Order, OrderDetail
from user.models import CustomerUser
from product.models import Product
class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = "__all__"
        widget ={
                user:= forms.ModelChoiceField(
                    queryset = CustomerUser.objects.all(), 
                    label="User",
                    widget=forms.Select(
                                attrs={
                                    'placeholder': 'CustomerUser', 'class': 'form-control'}),
                                required=True
                    )
        }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user'].widget.attrs['style'] = 'width:100px !important;'
        self.fields['name_receive'].widget.attrs.update({'class': 'form-control'})
        self.fields['phone_number'].widget.attrs.update({'class': 'form-control'})
        self.fields['shipping_address'].widget.attrs.update({'class': 'form-control'})
        self.fields['order_description'].widget.attrs.update({'class': 'form-control'})
        self.fields['is_completed'].widget.attrs.update({'class': 'form-check-input'})

class OrderDetailForm(forms.ModelForm):
    class Meta:
        model = OrderDetail
        fields = "__all__"
        widget ={
                order:= forms.ModelChoiceField(
                    queryset = Order.objects.all(), 
                    label="Order",
                    widget=forms.Select(
                                attrs={
                                    'placeholder': 'Order', 'class': 'form-control'}),
                                required=True
                    ),
                product:= forms.ModelChoiceField(
                    queryset = Product.objects.all(), 
                    label="Product",
                    widget=forms.Select(
                                attrs={
                                    'placeholder': 'Product', 'class': 'form-control'}),
                                required=True
                    )
        }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['order_id'].widget.attrs['style'] = 'width:100px !important;'
        self.fields['pro_id'].widget.attrs['style'] = 'width:100px !important;'
        self.fields['number'].widget.attrs.update({'class': 'form-control'})
        self.fields['address_delivery'].widget.attrs.update({'class': 'form-control'})

order/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Order, OrderDetail
from .forms import OrderForm, OrderDetailForm
from django.views import View
from product.models import Product, Category
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from product.views import Cart
# Create your views here.
def getTotal(cart):
    s = 0
    for key, value in cart.items():
        s += cart[key]['total']
    return s
@login_required(login_url='/user/login/')
def CreateOrder(request):
    temp_cart = request.session['cart']
    if request.method == "POST": 
        name = request.POST["name_receive"]
        phone = int(request.POST["phone_number"])
        user = request.user.id
        add = request.POST["address_receive"]
        des = request.POST["description"]
        total = getTotal(temp_cart)
        order = Order(user = user, phone_number = phone, shipping_address = add, order_description = des, name_receive = name, total_price = total)
        order.save()
        for key, value in temp_cart.items():
            orderDetail = OrderDetail(order_id= order.id, pro_name = temp_cart[key]['name'], amount = temp_cart[key]['number'], address_delivery = add,money = temp_cart[key]['price'], total_money = temp_cart[key]['total'])
            orderDetail.save()
        del request.session['cart']
        request.session.modified = True
        return redirect('/product/')
    else:
        return HttpResponse('Invalid data input')
class CreateOrderAll(LoginRequiredMixin, View):
    login_url = '/user/login/'
    def get(self, request):
        if request.user.is_superuser:
            order = Order.objects.all()
        else:
            id = request.user.id
            order = Order.objects.filter(user=id)
        if 'cart' not in request.session:
            request.session['cart'] = {}
        qs1 = Category.objects.values("id", "title")
        qs = Product.objects.all()
        checkAdmin = request.user.is_superuser
        numberOrder = 0
        if request.user.is_authenticated:
            id = request.user.id
            numberOrder = Order.objects.filter(user=id, is_completed = False).count()
        return render(request, 'order/order.html', { "numberOrder": numberOrder,'products': qs,'category_title': qs1, 'checkAdmin': checkAdmin, "cart": len(request.session['cart']), 'order': order, "number_order": len(order)})

class GetOrderDetail(LoginRequiredMixin, View):
    login_url = '/user/login/'
    def get(self, request, id):
        order = OrderDetail.objects.all()
        buy = Order.objects.get(id=id)
        if 'cart' not in request.session:
            request.session['cart'] = {}
        qs1 = Category.objects.values("id", "title")
        qs = Product.objects.all()
        checkAdmin = request.user.is_superuser
        order_detail = []
        for item in order:
            if id == item.order_id:
                order_detail.append(item)
        numberOrder = 0
        if request.user.is_authenticated:
            id = request.user.id
            numberOrder = Order.objects.filter(user=id, is_completed = False).count()
        return render(request, 'order/order-detail.html', { "numberOrder": numberOrder, 'products': qs,'category_title': qs1, 'checkAdmin': checkAdmin, "cart": len(request.session['cart']), 'order_detail': order_detail, "buy": buy.is_delivered})

def ConfirmOrder(request, id):
    order = Order.objects.get(id = id)
    order.is_delivered = True
    order.save()
    return redirect('/order/all-order/')
def DeleteOrderDetail(request, id):
    orderDetail = OrderDetail.objects.get(id = id)
    key = orderDetail.order_id
    orderDetail.delete()
    objects = OrderDetail.objects.filter(order_id = key)
    count = 0
    for item in objects:
        count += item.total_money
    if count == 0:
        Order.objects.get(id = key).delete()
    else:
        Order.objects.filter(id = key).update(total_price=count)
    return redirect('/order/all-order/')
def OrderComplete(request, id):
    order = Order.objects.get(id = id)
    order.is_completed = True
    order.save()
    return redirect('/order/all-order/')

order/templates/order/index.html
{% extends "homepage/base.html" %}
{% load static %}


{% block cssblock %}
<link rel="stylesheet" href="{% static 'product/style.css' %}">
{% endblock %}


{% block content %}
<div class="items-product container">
    <h1 class="title_item">Order</h1>
    <form action="{% url 'Product:add-product' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Title</label>
            {{f.order_id}}
            <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
        </div>

        <div class="mb3">
            <label for="exampleInputEmail1" class="form-label">Description</label>
            {{f.pro_id}}
        </div>

        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Category: </label>
            {{f.number}}
        </div>

        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Price</label>
            {{f.address_delivery}}
            <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}
{% block jsblock %}
<script src="{% static 'product/app.js' %}">
</script>
{% endblock %}

order/templates/order/order-detail.html
{% extends "homepage/base.html" %}
{% load static %}


{% block cssblock %}
<link rel="stylesheet" href="{% static 'order/style.css' %}">
{% endblock %}


{% block content %}
<div class="container">
    <div class="d-flex justify-content-center row">
        <div class="col-md-12">
            <div class="rounded">
                <div class="table-responsive table-borderless">
                    <h2 class="text-center mb-5">YOUR ORDER DETAIL</h2>
                    <table class="table text-center mt-2">
                        <thead>
                            <tr>
                                <th>ID Order</th>
                                <th>Name product</th>
                                <th>Price</th>
                                <th>Number</th>
                                <th>Total Money</th>
                                <th>Address</th>
                                {% if checkAdmin %}
                                    <th>Option</th>
                                {% else %}
                                    <th>Option</th>
                                {% endif %}
                            </tr>
                        </thead>
                        <tbody class="table-body" >
                            {% for item in order_detail %}
                                <tr class="cell-1 ">
                                    <td>{{ item.order_id }}</td>
                                    <td>{{ item.pro_name }}</td>
                                    <td>{{ item.money }}</td>
                                    <td>{{ item.amount }}</td>
                                    <td>{{ item.total_money }}</td>
                                    <td>{{ item.address_delivery }}</td>
                                    {% if not checkAdmin %}
                                        {% if not buy %}
                                            <td><a href="{% url 'Order:delete-order-detail' item.id %}"><button type="button" class="btn btn-danger">Delete</button></a></td>
                                        {% else %}
                                            <td><a href=""><button type="button" class="btn btn-success"> Delivery </button></a></td>
                                        {% endif %}
                                    {% else %}
                                        {% if not buy %}
                                            <td><a href="{% url 'Order:confirm-order' item.order_id %}"><button type="button" class="btn btn-success">Confirm order</button></a></td>
                                        {% else %}
                                            <td><a href=""><button type="button" class="btn btn-success"> Delivery </button></a></td>
                                        {% endif %}
                                    {% endif %}
                                </tr>
                            {% endfor %}
                            
                        </tbody>
                        
                    </table>    
                    {% if checkAdmin %}
                        <p class="text-danger">**Note: item validation for all</p> 
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block jsblock %}
<script src="{% static 'product/app.js' %}">
</script>
{% endblock %}

order/templates/order/order.html
{% extends "homepage/base.html" %}
{% load static %}


{% block cssblock %}
<link rel="stylesheet" href="{% static 'order/style.css' %}">
{% endblock %}


{% block content %}
<div class="container">
    <div class="d-flex justify-content-center row">
        <div class="col-md-12">
            <div class="rounded">
                <div class="table-responsive table-borderless">
                    {% if number_order > 0 %}
                    <h2 class="text-center mb-5">YOUR ORDER</h2>
                    <table class="table text-center mt-2">
                        <thead>
                            <tr>
                                <th>ID USER</th>
                                <th>Phone number</th>
                                <th>Consignee's name</th>
                                <th>Address</th>
                                <th>Description</th>
                                <th>Total price</th>
                                <th>Status</th>
                                {% if not checkAdmin %}
                                    <th>Customer</th>
                                {% endif %}
                                </th>
                            </tr>
                        </thead>
                        <tbody class="table-body" >
                            {% for item in order %}
                                <tr class="cell-1 ">
                                    <td>{{ item.user }}</td>
                                    <td>{{ item.phone_number }}</td>
                                    <td>{{ item.name_receive }}</td>
                                    <td>{{ item.shipping_address }}</td>
                                    <td>{{ item.order_description }}</td>
                                    <td>{{ item.total_price }}</td>
                                    {% if checkAdmin %}
                                        {% if item.is_delivered %}
                                            <td> <a href="{% url 'Order:order-detail' item.id %}"><button type="button" class="btn btn-primary">Delivery</button></a></td>
                                        {% else %}
                                            <td> <a href="{% url 'Order:order-detail' item.id %}"><button type="button" class="btn btn-success">Detail</button></a></td>
                                        {% endif %}
                                    {% else %}
                                        {% if item.is_delivered %}
                                            <td> <a href="{% url 'Order:order-detail' item.id %}"><button type="button" class="btn btn-success">Delivery</button></a></td>
                                        {% else %}
                                            <td> <a href="{% url 'Order:order-detail' item.id %}"><button type="button" class="btn btn-warning">Wait</button></a></td>
                                        {% endif %}
                                    {% endif %}
                                    {% if not checkAdmin %}
                                        {% if item.is_completed and item.is_delivered %}
                                            <td> <a href="{% url 'Order:order-detail' item.id %}"><button type="button" class="btn btn-primary">Done</button></a></td>
                                        {% else %}
                                            {% if item.is_delivered %}
                                                <td> <a href="{% url 'Order:order-complete' item.id %}"><button type="button" class="btn btn-success">Received</button></a></td>
                                            {% endif %}  
                                        {% endif %}
                                    {% endif %}
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% else %}
                        <div class="card">
                        <div class="card-body cart">
                                <div class="col-sm-12 empty-cart-cls text-center">
                                    <img src="https://i.imgur.com/dCdflKN.png" width="130" height="130" class="img-fluid mb-4 mr-3">
                                    <h3><strong>Your Order is Empty</strong></h3>
                                    <h4>Add something to make me happy :)</h4>
                                </div>
                        </div>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block jsblock %}
<script src="{% static 'product/app.js' %}">
</script>
{% endblock %}